<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Migration\TimeTrackerMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240306230725 extends TimeTrackerMigration
{
    public function getDescription(): string
    {
        return 'Update uuid types';
    }

    public function upPostgresql(Schema $schema): void
    {
        $this->addSql('ALTER TABLE note ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE note ALTER assigned_to_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN note.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN note.assigned_to_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE statistic ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE statistic ALTER assigned_to_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN statistic.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN statistic.assigned_to_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE statistic_value ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE statistic_value ALTER statistic_id TYPE UUID');
        $this->addSql('ALTER TABLE statistic_value ALTER time_entry_id TYPE UUID');
        $this->addSql('ALTER TABLE statistic_value ALTER timestamp_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN statistic_value.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN statistic_value.statistic_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN statistic_value.time_entry_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN statistic_value.timestamp_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE tag ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE tag ALTER assigned_to_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN tag.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag.assigned_to_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE tag_link ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE tag_link ALTER time_entry_id TYPE UUID');
        $this->addSql('ALTER TABLE tag_link ALTER timestamp_id TYPE UUID');
        $this->addSql('ALTER TABLE tag_link ALTER tag_id TYPE UUID');
        $this->addSql('ALTER TABLE tag_link ALTER task_id TYPE UUID');
        $this->addSql('ALTER TABLE tag_link ALTER statistic_id TYPE UUID');
        $this->addSql('ALTER TABLE tag_link ALTER note_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN tag_link.time_entry_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag_link.timestamp_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag_link.tag_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag_link.task_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag_link.statistic_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag_link.note_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE task ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE task ALTER assigned_to_id TYPE UUID');
        $this->addSql('ALTER TABLE task ALTER parent_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN task.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN task.assigned_to_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN task.parent_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE time_entry ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE time_entry ALTER assigned_to_id TYPE UUID');
        $this->addSql('ALTER TABLE time_entry ALTER task_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN time_entry.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN time_entry.assigned_to_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN time_entry.task_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE timestamp ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE timestamp ALTER assigned_to_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN timestamp.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN timestamp.assigned_to_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE users ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN users.id IS \'(DC2Type:uuid)\'');
    }

    public function downPostgresql(Schema $schema): void
    {
        $this->addSql('ALTER TABLE tag ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE tag ALTER assigned_to_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN tag.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag.assigned_to_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE tag_link ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE tag_link ALTER time_entry_id TYPE UUID');
        $this->addSql('ALTER TABLE tag_link ALTER timestamp_id TYPE UUID');
        $this->addSql('ALTER TABLE tag_link ALTER task_id TYPE UUID');
        $this->addSql('ALTER TABLE tag_link ALTER note_id TYPE UUID');
        $this->addSql('ALTER TABLE tag_link ALTER tag_id TYPE UUID');
        $this->addSql('ALTER TABLE tag_link ALTER statistic_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN tag_link.time_entry_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag_link.timestamp_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag_link.task_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag_link.note_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag_link.tag_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN tag_link.statistic_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE time_entry ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE time_entry ALTER assigned_to_id TYPE UUID');
        $this->addSql('ALTER TABLE time_entry ALTER task_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN time_entry.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN time_entry.assigned_to_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN time_entry.task_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE task ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE task ALTER assigned_to_id TYPE UUID');
        $this->addSql('ALTER TABLE task ALTER parent_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN task.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN task.assigned_to_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN task.parent_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE note ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE note ALTER assigned_to_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN note.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN note.assigned_to_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE timestamp ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE timestamp ALTER assigned_to_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN timestamp.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN timestamp.assigned_to_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE statistic_value ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE statistic_value ALTER statistic_id TYPE UUID');
        $this->addSql('ALTER TABLE statistic_value ALTER time_entry_id TYPE UUID');
        $this->addSql('ALTER TABLE statistic_value ALTER timestamp_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN statistic_value.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN statistic_value.statistic_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN statistic_value.time_entry_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN statistic_value.timestamp_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE statistic ALTER id TYPE UUID');
        $this->addSql('ALTER TABLE statistic ALTER assigned_to_id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN statistic.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN statistic.assigned_to_id IS \'(DC2Type:uuid)\'');

        $this->addSql('ALTER TABLE users ALTER id TYPE UUID');
        $this->addSql('COMMENT ON COLUMN users.id IS \'(DC2Type:uuid)\'');
    }

    protected function upMysql(Schema $schema): void
    {

    }

    protected function downMysql(Schema $schema): void
    {

    }

    public function upSqlite(Schema $schema): void
    {

    }

    public function downSqlite(Schema $schema): void
    {

    }
}
